# Generated by Django 6.0 on 2026-02-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
