# Generated by Django 5.2.8 on 2026-03-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
